name: Dependabot reviewer
on: pull_request
permissions:
  pull-requests: write
  contents: write
jobs:
  call-workflow-passing-data:
    uses: grafana/security-github-actions/.github/workflows/dependabot-automerge.yaml@main
    with:
      packages-minor-autoupdate: '["semver","tslib"]'
      repository-merge-method: 'squash'
