name: release
on:
  push:
    branches:
      - main

jobs:
  npm-publish:
    name: Publish to NPM & GitHub Package Registry
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version_check.outputs.version }}
      version_changed: ${{ steps.version_check.outputs.changed }}
    permissions:
      contents: write
      # id-token: write is required for the get-vault-secrets step
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: false
      # limit releases to version changes - https://github.com/EndBug/version-check
      - name: Check version changes
        uses: EndBug/version-check@36ff30f37c7deabe56a30caa043d127be658c425 # v2.1.5
        id: version_check
        with:
          file-url: https://unpkg.com/@grafana/async-query-data@latest/package.json
          static-checking: localIsNew

      - name: Version update detected
        if: steps.version_check.outputs.changed == 'true'
        env:
          NEW_VERSION: ${{ steps.version_check.outputs.version }}
          VERSION_TYPE: ${{ steps.version_check.outputs.type }}
        run: 'echo "Version change found! New version: ${NEW_VERSION} (${VERSION_TYPE})"'

      - name: Setup .npmrc file for NPM registry
        if: steps.version_check.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        if: steps.version_check.outputs.changed == 'true'
        run: yarn

      - name: Build library
        if: steps.version_check.outputs.changed == 'true'
        run: yarn build

      - name: Get secrets from vault
        id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@main
        with:
          repo_secrets: |
            NPM_TOKEN=npm-release.npm_token

      - name: Publish package to NPM
        if: steps.version_check.outputs.changed == 'true'
        run: npm publish --access public --scope grafana
        env:
          NODE_AUTH_TOKEN: ${{ env.NPM_TOKEN }}

      - name: Setup .npmrc file for GitHub Packages
        if: steps.version_check.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@grafana'

      - name: Publish package to Github Packages
        if: steps.version_check.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: npm-publish
    if: needs.npm-publish.outputs.version_changed == 'true'
    env:
      NEW_VERSION: ${{ needs.npm-publish.outputs.new_version }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Create Release Notes
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.request(`POST /repos/${{ github.repository }}/releases`, {
              tag_name: "v${NEW_VERSION}",
              generate_release_notes: true
            });
